var tags=[ { key: 'Fixed Access', value: 14 },
  { key: 'Call Recording', value: 6 },
  { key: 'Routing', value: 6 },
  { key: 'Mobile Access Connectivity', value: 6 },
  { key: 'Remote connectiviity', value: 5 },
  { key: 'WAN Core', value: 4 },
  { key: 'Analytics', value: 4 },
  { key: 'Instant Messaging', value: 4 },
  { key: 'Telephony', value: 4 },
  { key: 'Call Back', value: 3 },
  { key: 'Presence', value: 3 },
  { key: 'Web Chat', value: 3 },
  { key: 'Sharing', value: 3 },
  { key: 'Interactive Voice Response', value: 3 },
  { key: 'Directory Service', value: 3 },
  { key: 'Media Conferencing', value: 3 },
  { key: 'Email', value: 2 },
  { key: 'Managed Mobile', value: 2 },
  { key: 'Survey', value: 2 },
  { key: 'Faciliates and Equipment Management', value: 2 },
  { key: 'Usage Sharing', value: 2 },
  { key: 'SIP', value: 2 },
  { key: 'Campaign Management', value: 2 },
  { key: 'Mobile Service', value: 2 },
  { key: 'PSTN Calling Service', value: 2 },
  { key: 'Managed WAN', value: 2 },
  { key: 'Managed WiFi', value: 2 },
  { key: 'Speech Recognition Capability', value: 2 },
  { key: 'Biometric Capability', value: 2 },
  { key: 'Managed LAN', value: 2 },
  { key: 'SIP third party', value: 2 },
  { key: 'LAN Port Configuration', value: 2 },
  { key: 'Efax Service', value: 2 },
  { key: 'Virtual Encryption Domain', value: 2 },
  { key: 'SMS', value: 2 },
  { key: 'Toll Free', value: 1 },
  { key: 'Self Service Access Control', value: 1 },
  { key: 'ISDN Access', value: 1 },
  { key: 'Authentication', value: 1 },
  { key: 'Video', value: 1 },
  { key: 'Integrated knowledge base', value: 1 },
  { key: 'Equipment as a service', value: 1 },
  { key: 'Legacy Gateway Interconnect', value: 1 },
  { key: 'Work force management', value: 1 },
  { key: 'Social Media', value: 1 },
  { key: 'SMS and Routing', value: 1 },
  { key: 'Selectable Power Module', value: 1 },
  { key: 'VoiceMail', value: 1 },
  { key: 'Managed Public Key Infrastructure', value: 1 } ]
